version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3.0-node-browsers
      - image: circleci/mariadb:10.4
    environment:
      - DB_CONNECTION: circle_testing

    steps:
      - checkout
      - run:
          name: Update apt-get
          command: sudo apt-get update
      # - run:
      #     name: Docker php extensions install
      #     command: sudo docker-php-ext-install pdo_mysql
      - run:
          name: Setup docker
          command: |
            docker compose build
            docker compose up -d
            docker compose run app composer install
      - run:
          name: Setup Laravel1
          working_directory: backend
          command: |
            cp .env.testing .env
      - run:
          name: Setup Laravel2
          command: |
            docker compose exec app php artisan key:generate
            docker compose exec app php artisan migrate:refresh --seed
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "backend/composer.json" }}
      #       - v1-dependencies-
      # - run:
      #     name: Install PHP libraries
      #     working_directory: backend
      #     command: composer install -n --prefer-dist
      # - save_cache:
      #     paths:
      #       - ./vendor
      #     key: v1-dependencies-{{ checksum "backend/composer.json" }}
      - run:
          working_directory: backend
          name: Run PHPUnit
          command: docker compose exec app vendor/bin/phpUnit